// animedekho-resolver — Cloudflare Worker
const ANIMESALT_API='https://aniversee.vercel.app/api/animesalt';
const ANIMEDEKHO_API='https://animedekho-api.pages.dev/api/embed';
const TOONAPI='https://toonapi.apiplay.workers.dev/api/embed';
const ANIMESALT_SITE='https://animesalt.link';
const VIDSTREAM_HOST='https://as-cdn21.top';
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,HEAD,OPTIONS','Access-Control-Allow-Headers':'*','Access-Control-Expose-Headers':'*','Vary':'Origin'};
const UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124 Safari/537.36';
addEventListener('fetch',e=>e.respondWith(handleRequest(e.request)));
async function handleRequest(request){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});const {pathname}=new URL(request.url);if(pathname==='/vidstream')return handleVidstream(request);if(pathname==='/m3u8')return handleM3u8(request);if(pathname==='/proxy')return handleProxy(request);return handleResolve(request)}
async function handleVidstream(request){const {searchParams,origin}=new URL(request.url);const hash=searchParams.get('hash');if(!hash)return errResp('?hash= required',400);const referer=`${VIDSTREAM_HOST}/video/${hash}`;try{const r=await fetch(`${VIDSTREAM_HOST}/player/index.php?data=${hash}&do=getVideo`,{method:'POST',headers:{'X-Requested-With':'XMLHttpRequest',Referer:referer,'User-Agent':UA}});const d=await r.json();const u=d?.videoSource||d?.securedLink;if(!u)return errResp('no m3u8 in getVideo response',404);return handleM3u8(new Request(`${origin}/m3u8?url=${encodeURIComponent(u)}&referer=${encodeURIComponent(referer)}`,request))}catch(e){return errResp('getVideo failed: '+e.message,502)}}
async function handleM3u8(request){const {searchParams,origin}=new URL(request.url);const raw=searchParams.get('url');const referer=searchParams.get('referer')||'';if(!raw)return errResp('?url= required',400);let url;try{url=decodeURIComponent(raw)}catch{url=raw}try{const r=await fetch(url,{headers:{Referer:referer,'User-Agent':UA,Accept:'*/*'}});if(!r.ok)return errResp(`upstream ${r.status}`,r.status);const text=await r.text();const rewritten=text.split('\n').map(line=>{const t=line.trim();if(!t)return line;if(t.startsWith('#EXT-X-MAP:'))return t.replace(/URI=\"([^\"]+)\"/,( _,u)=>`URI=\"${mkProxy(origin,absUrl(url,u),referer)}\"`);if(t.startsWith('#EXT-X-MEDIA:')&&t.includes('URI=\"'))return t.replace(/URI=\"([^\"]+)\"/,( _,u)=>`URI=\"${mkM3u8(origin,absUrl(url,u),referer)}\"`);if(t.startsWith('#'))return line;const abs=absUrl(url,t);return abs.includes('.m3u8')?mkM3u8(origin,abs,referer):mkProxy(origin,abs,referer)}).join('\n');return new Response(rewritten,{headers:{...CORS,'Content-Type':'application/vnd.apple.mpegurl'}})}catch(e){return errResp('fetch failed: '+e.message,502)}}
async function handleProxy(request){const {searchParams}=new URL(request.url);const target=searchParams.get('url');const referer=searchParams.get('referer')||'';if(!target)return errResp('?url= required',400);let decoded;try{decoded=decodeURIComponent(target)}catch{decoded=target}let lastErr=null;for(let i=0;i<3;i++){try{if(i)await sleep(500*i);const up=await fetch(decoded,{headers:{'User-Agent':UA,Accept:'*/*',...(referer?{Referer:referer,Origin:new URL(referer).origin}: {})}});if(up.status===429||up.status>=500){lastErr=new Error('upstream '+up.status);continue}const h=new Headers(CORS);h.set('Content-Type',up.headers.get('Content-Type')||'application/octet-stream');return new Response(up.body,{status:up.status,headers:h})}catch(e){lastErr=e}}return errResp(lastErr?.message||'proxy failed',502)}
function isValidEmbed(raw){try{const u=new URL(raw);if(!/^https?:$/i.test(u.protocol))return false;const s=`${u.hostname}${u.pathname}${u.search}`.toLowerCase();if(/\.(css|js|mjs|json|png|jpe?g|gif|webp|svg|ico|woff2?|ttf|otf)(?:$|[?#])/i.test(s))return false;if(/googletagmanager|google-analytics|image\.tmdb\.org|img\.animesalt\.link/i.test(s))return false;if(/animesalt\.link\/(?:$|series\/|episodes?\/|movies?\/|category\/|wp-content\/|wp-includes\/)/i.test(s))return false;if(/(?:^|[/?])(?:download|dl)(?:[/?]|\.)/i.test(u.pathname))return false;return /(?:iframe|embed|player|play|mystream|abyss|megacloud|vidstream|multi-lang-plyr|modalclonism|quiahussars)/i.test(s)||!/animesalt\.link$/i.test(u.hostname)}catch{return false}}
function isApiEmbed(raw){try{const u=new URL(raw);return /^https?:$/i.test(u.protocol)&&!/\.(css|js|mjs|json|png|jpe?g|gif|webp|svg|ico|woff2?|ttf|otf)(?:$|[?#])/i.test(u.pathname)}catch{return false}}
function extractAnimeSaltDownloads(html){const out=[];const seen=new Set();const add=(raw,label='AnimeSalt Download')=>{const u=absUrl(ANIMESALT_SITE,decodeHtml(raw));if(!/^https?:/i.test(u)||seen.has(u))return;const low=u.toLowerCase();if(/googletagmanager|google-analytics|\.(css|js|mjs|png|jpe?g|gif|webp|svg|ico|woff2?|ttf|otf)(?:$|[?#])/i.test(low))return;if(!/(?:trdownload|download|dl\.php|download\/|dl2\.php)/i.test(u))return;seen.add(u);out.push({name:label.trim()||'AnimeSalt Download',url:u,provider:'AnimeSalt'})};for(const m of html.matchAll(/<(?:a|button)[^>]*(?:href|data-url|data-download|data-href)=[\"']([^\"']+)[\"'][^>]*>([\s\S]{0,300})<\/(?:a|button)>/gi)){const label=m[2].replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();add(m[1],label)}for(const m of html.matchAll(/(?:https?:)?\/\/[^\"'<>\s]+/gi))add(m[0]);return out}
async function extractAnimeSaltPageData(slug){try{if(!slug)return{servers:[],downloads:[]};const out={servers:[],downloads:[]};const seen=new Set();for(const target of [`${ANIMESALT_SITE}/episode/${encodeURIComponent(slug)}/`,`${ANIMESALT_SITE}/episodes/${encodeURIComponent(slug)}/`]){const r=await fetch(target,{headers:{'User-Agent':UA,'Accept':'text/html,application/xhtml+xml'}});if(!r.ok)continue;const html=await r.text();out.downloads.push(...extractAnimeSaltDownloads(html));const add=raw=>{const u=absUrl(ANIMESALT_SITE,decodeHtml(raw));if(!isValidEmbed(u)||seen.has(u))return;seen.add(u);out.servers.push({provider:'AnimeSalt',name:'Iframe',type:'multi',embedUrl:u})};for(const m of html.matchAll(/<iframe[^>]+(?:src|data-src|data-url|data-embed|data-iframe|data-player)=[\"']([^\"']+)[\"'][^>]*>/gi))add(m[1]);for(const m of html.matchAll(/data-(?:src|url|embed|iframe|player)=[\"']([^\"']+)[\"']/gi))add(m[1]);if(out.servers.length||out.downloads.length)break}out.downloads=[...new Map(out.downloads.map(x=>[x.url,x])).values()];return out}catch{return{servers:[],downloads:[]}}}
async function handleResolve(request){const {searchParams,origin}=new URL(request.url);const slug=searchParams.get('slug');const anilistId=searchParams.get('anilistId')||'';const ep=searchParams.get('ep');const season=searchParams.get('season');const saltId=searchParams.get('saltId');const isMovie=searchParams.get('type')==='movie'||(!ep&&!season&&!/(?:s?\d{1,3}x\d{1,5}|(?:episode|ep)[-_ ]?\d+)/i.test(slug||''));if(!slug)return errResp('missing ?slug=',400);const parsed=parseSlugEpisode(slug);const effectiveEp=ep||(!isMovie?parsed.ep:'');const effectiveSeason=season||(!isMovie?parsed.season:'');const effectiveSaltId=saltId||parsed.saltId||slug;const results={slug,media:isMovie?'movie':'episode',servers:[],m3u8s:[],downloads:[]};const [dekho,toon]=await Promise.all([fetchJSON(`${ANIMEDEKHO_API}/${encodeURIComponent(slug)}`),isMovie?Promise.resolve(null):fetchJSON(`${TOONAPI}/${encodeURIComponent(slug)}`)]);for(const {name,data,type} of [{name:'AnimeDekho',data:dekho,type:isMovie?'multi':'sub'},{name:'ToonAPI',data:toon,type:'multi'}]){if(!data?.servers)continue;for(const s of data.servers){if(!s?.url)continue;const sType=detectType(s.name,type);const entry={provider:isMovie?`${name} · Movie`:name,name:s.name,type:sType,embedUrl:s.url};const hash=extractHash(s.url);if(hash){entry.m3u8=`${origin}/vidstream?hash=${hash}`;results.m3u8s.push({provider:`${name} · ${s.name}`,type:sType,m3u8:entry.m3u8})}results.servers.push(entry)}for(const d of(data.downloads||[]))if(d?.url)results.downloads.push({name:d.name,url:d.url,provider:name})}
if(!isMovie){const saltRequests=[];if(effectiveSaltId&&effectiveEp){const base=`${ANIMESALT_API}?ep=${encodeURIComponent(effectiveEp)}&season=${encodeURIComponent(effectiveSeason||'')}&saltId=${encodeURIComponent(effectiveSaltId)}&slug=${encodeURIComponent(slug)}`;saltRequests.push(fetchJSON(anilistId?`${base}&anilistId=${encodeURIComponent(anilistId)}`:base))}saltRequests.push(extractAnimeSaltPageData(slug));const [saltApi,saltPage]=await Promise.all(saltRequests);
// IMPORTANT: API embeds are trusted separately from scraped HTML. Do not run isValidEmbed() on them.
for(const s of Array.isArray(saltApi?.servers)?saltApi.servers:[]){const url=s?.url||s?.embedUrl||s?.embed||s?.iframe||s?.src||s?.link;if(!url||!isApiEmbed(url))continue;const name=s?.name||s?.title||s?.server||'AnimeSalt';if(!results.servers.some(x=>x.embedUrl===url))results.servers.push({provider:'AnimeSalt',name,type:detectType(name,'multi'),embedUrl:url})}
for(const s of Array.isArray(saltPage?.servers)?saltPage.servers:[])if(s?.embedUrl&&!results.servers.some(x=>x.embedUrl===s.embedUrl))results.servers.push(s);
for(const d of [...(Array.isArray(saltApi?.downloads)?saltApi.downloads:[]),...(Array.isArray(saltPage?.downloads)?saltPage.downloads:[])]){const url=d?.url||d?.href||d?.link;if(!url)continue;const clean=absUrl(ANIMESALT_SITE,decodeHtml(url));if(!results.downloads.some(x=>x.url===clean))results.downloads.push({name:d?.name||d?.title||'AnimeSalt Download',url:clean,provider:'AnimeSalt'})}}
if(isMovie){const movieServers=await extractMoviePageServers(effectiveSaltId);for(const s of movieServers)if(!results.servers.some(x=>x.embedUrl===s.embedUrl))results.servers.push(s)}results.downloads=[...new Map(results.downloads.map(x=>[x.url,x])).values()];results.total=results.servers.length;return jsonResp(results)}
async function extractMoviePageServers(slug){try{const r=await fetch(`${ANIMESALT_SITE}/movies/${encodeURIComponent(slug)}/`,{headers:{'User-Agent':UA,'Accept':'text/html'}});if(!r.ok)return[];const html=await r.text(),out=[],seen=new Set();for(const m of html.matchAll(/<iframe[^>]+(?:src|data-src|data-url|data-embed|data-player)=[\"']([^\"']+)[\"'][^>]*>/gi)){const u=absUrl(ANIMESALT_SITE,decodeHtml(m[1]));if(isValidEmbed(u)&&!seen.has(u)){seen.add(u);out.push({provider:'AnimeSalt · Movie',name:'Iframe',type:'embed',embedUrl:u})}}return out}catch{return[]}}
function parseSlugEpisode(slug){const s=decodeURIComponent(slug||'').replace(/\/$/,'');const m=s.match(/(?:^|[-_\s])s?(\d{1,3})x(\d{1,5})(?:[-_\s]|$)/i);if(m)return{season:m[1],ep:m[2],saltId:s.replace(new RegExp(`[-_]?s?${m[1]}x${m[2]}$`,'i'),'')};const m2=s.match(/(?:episode|ep)[-_\s:]*(\d{1,5})/i);return{season:'1',ep:m2?.[1]||'1',saltId:s.replace(/(?:[-_]?episode|[-_]?ep)[-_\s:]*(\d{1,5})$/i,'')||s}}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}function mkProxy(origin,url,ref){return `${origin}/proxy?url=${encodeURIComponent(url)}&referer=${encodeURIComponent(ref)}`}function mkM3u8(origin,url,ref){return `${origin}/m3u8?url=${encodeURIComponent(url)}&referer=${encodeURIComponent(ref)}`}function absUrl(base,u){try{return new URL(u,base).href}catch{return u}}function decodeHtml(s){return String(s||'').replace(/&amp;/g,'&').replace(/&quot;/g,'\"').replace(/&#x27;/gi,"'").replace(/&#39;/g,"'")}
function extractHash(url){const m=url.match(/as-cdn\d+\.top\/video\/([a-f0-9]{32})/i);return m?m[1]:null}function detectType(name,fb){const n=(name||'').toLowerCase();return n.includes('dub')?'dub':n.includes('sub')?'sub':fb}async function fetchJSON(url){try{const r=await fetch(url,{headers:{'User-Agent':UA}});if(!r.ok)return null;return r.json()}catch{return null}}function jsonResp(data,status){return new Response(JSON.stringify(data,null,2),{status:status||200,headers:{...CORS,'Content-Type':'application/json','Cache-Control':'no-store'}})}function errResp(msg,status){return jsonResp({error:msg},status||400)}
