// animedekho-resolver — Cloudflare Worker
const ANIMEDEKHO_API='https://animedekho-api.pages.dev/api/embed';
const TOONAPI='https://toonapi.apiplay.workers.dev/api/embed';
const VIDSTREAM_HOST='https://as-cdn21.top';
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,HEAD,OPTIONS','Access-Control-Allow-Headers':'*','Access-Control-Expose-Headers':'*','Vary':'Origin'};
const UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124 Safari/537.36';
addEventListener('fetch',e=>e.respondWith(handleRequest(e.request)));
async function handleRequest(request){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});const {pathname}=new URL(request.url);if(pathname==='/vidstream')return handleVidstream(request);if(pathname==='/m3u8')return handleM3u8(request);if(pathname==='/proxy')return handleProxy(request);return handleResolve(request)}
async function handleVidstream(request){const {searchParams,origin}=new URL(request.url);const hash=searchParams.get('hash');if(!hash)return errResp('?hash= required',400);const referer=`${VIDSTREAM_HOST}/video/${hash}`;try{const r=await fetch(`${VIDSTREAM_HOST}/player/index.php?data=${hash}&do=getVideo`,{method:'POST',headers:{'X-Requested-With':'XMLHttpRequest',Referer:referer,'User-Agent':UA}});const d=await r.json();const u=d?.videoSource||d?.securedLink;if(!u)return errResp('no m3u8 in getVideo response',404);return handleM3u8(new Request(`${origin}/m3u8?url=${encodeURIComponent(u)}&referer=${encodeURIComponent(referer)}`,request))}catch(e){return errResp('getVideo failed: '+e.message,502)}}
async function handleM3u8(request){const {searchParams,origin}=new URL(request.url);const raw=searchParams.get('url');const referer=searchParams.get('referer')||'';if(!raw)return errResp('?url= required',400);let url;try{url=decodeURIComponent(raw)}catch{url=raw}try{const r=await fetch(url,{headers:{Referer:referer,'User-Agent':UA,Accept:'*/*'}});if(!r.ok)return errResp(`upstream ${r.status}`,r.status);const text=await r.text();const rewritten=text.split('\n').map(line=>{const t=line.trim();if(!t)return line;if(t.startsWith('#EXT-X-MAP:'))return t.replace(/URI=\"([^\"]+)\"/,( _,u)=>`URI=\"${mkProxy(origin,absUrl(url,u),referer)}\"`);if(t.startsWith('#EXT-X-MEDIA:')&&t.includes('URI=\"'))return t.replace(/URI=\"([^\"]+)\"/,( _,u)=>`URI=\"${mkM3u8(origin,absUrl(url,u),referer)}\"`);if(t.startsWith('#'))return line;const abs=absUrl(url,t);return abs.includes('.m3u8')?mkM3u8(origin,abs,referer):mkProxy(origin,abs,referer)}).join('\n');return new Response(rewritten,{headers:{...CORS,'Content-Type':'application/vnd.apple.mpegurl'}})}catch(e){return errResp('fetch failed: '+e.message,502)}}
async function handleProxy(request){const {searchParams}=new URL(request.url);const target=searchParams.get('url');const referer=searchParams.get('referer')||'';if(!target)return errResp('?url= required',400);let decoded;try{decoded=decodeURIComponent(target)}catch{decoded=target}let lastErr=null;for(let i=0;i<3;i++){try{if(i)await sleep(500*i);const up=await fetch(decoded,{headers:{'User-Agent':UA,Accept:'*/*',...(referer?{Referer:referer,Origin:new URL(referer).origin}: {})}});if(up.status===429||up.status>=500){lastErr=new Error('upstream '+up.status);continue}const h=new Headers(CORS);h.set('Content-Type',up.headers.get('Content-Type')||'application/octet-stream');return new Response(up.body,{status:up.status,headers:h})}catch(e){lastErr=e}}return errResp(lastErr?.message||'proxy failed',502)}
async function handleResolve(request){const {searchParams,origin}=new URL(request.url);const slug=searchParams.get('slug');const ep=searchParams.get('ep');const season=searchParams.get('season');const isMovie=searchParams.get('type')==='movie'||(!ep&&!season&&!/(?:s?\d{1,3}x\d{1,5}|(?:episode|ep)[-_ ]?\d+)/i.test(slug||''));if(!slug)return errResp('missing ?slug=',400);const results={slug,media:isMovie?'movie':'episode',servers:[],m3u8s:[],downloads:[]};const [dekho,toon]=await Promise.all([fetchJSON(`${ANIMEDEKHO_API}/${encodeURIComponent(slug)}`),isMovie?Promise.resolve(null):fetchJSON(`${TOONAPI}/${encodeURIComponent(slug)}`)]);for(const {name,data,type} of [{name:'AnimeDekho',data:dekho,type:isMovie?'multi':'sub'},{name:'ToonAPI',data:toon,type:'multi'}]){if(!data?.servers)continue;for(const s of data.servers){if(!s?.url)continue;const sType=detectType(s.name,type);const entry={provider:isMovie?`${name} · Movie`:name,name:s.name,type:sType,embedUrl:s.url};const hash=extractHash(s.url);if(hash){entry.m3u8=`${origin}/vidstream?hash=${hash}`;results.m3u8s.push({provider:`${name} · ${s.name}`,type:sType,m3u8:entry.m3u8})}results.servers.push(entry)}for(const d of(data.downloads||[]))if(d?.url)results.downloads.push({name:d.name,url:d.url,provider:name})}results.total=results.servers.length;return jsonResp(results)}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}function mkProxy(origin,url,ref){return `${origin}/proxy?url=${encodeURIComponent(url)}&referer=${encodeURIComponent(ref)}`}function mkM3u8(origin,url,ref){return `${origin}/m3u8?url=${encodeURIComponent(url)}&referer=${encodeURIComponent(ref)}`}function absUrl(base,u){try{return new URL(u,base).href}catch{return u}}function extractHash(url){const m=url.match(/as-cdn\d+\.top\/video\/([a-f0-9]{32})/i);return m?m[1]:null}function detectType(name,fb){const n=(name||'').toLowerCase();return n.includes('dub')?'dub':n.includes('sub')?'sub':fb}async function fetchJSON(url){try{const r=await fetch(url,{headers:{'User-Agent':UA}});if(!r.ok)return null;return r.json()}catch{return null}}function jsonResp(data,status){return new Response(JSON.stringify(data,null,2),{status:status||200,headers:{...CORS,'Content-Type':'application/json','Cache-Control':'no-store'}})}function errResp(msg,status){return jsonResp({error:msg},status||400)}
